In [20]:
import pandas as pd
import numpy as np

data = {
    "name": ["William", "Emma", "Sofia", "Markus", "Edward", "Thomas", "Ethan", np.nan, "Arun", "Anika", "Paulo"],
    "region": [np.nan, "North", "East", np.nan, "West", "West", "South", np.nan, "West", "East", "South"],
    "sales": [50000.0, 52000.0, np.nan, np.nan, 42000.0, 72000.0, 49000.0, np.nan, 67000.0, 65000.0, 67000.0],
    "expenses": [42000.0, 43000.0, np.nan, np.nan, 38000.0, 39000.0, 42000.0, np.nan, 39000.0, 50000.0, 45000.0]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

Original DataFrame:
       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [16]:
df=df.dropna(how="all")

In [17]:
df

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [18]:
data = {
    "A": ["TeamA", "TeamB", "TeamB", "TeamC", "TeamA"],
    "B": [50, 40, 40, 30, 50],
    "C": [True, False, False, False, True]
}
df=pd.DataFrame(data)
df

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
2  TeamB  40  False
3  TeamC  30  False
4  TeamA  50   True

In [19]:
df.drop_duplicates()

       A   B      C
0  TeamA  50   True
1  TeamB  40  False
3  TeamC  30  False

In [31]:
df.dropna(subset=["region","expenses"])

      name region    sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [71]:
import os
os.chdir("D:/Yuvraj/LJ/LJ/PYTHON")

In [39]:
df=pd.read_csv("Datasets/auto-mpg.csv")
os.chdir("D:/Yuvraj/LJ/LJ/PYTHON/PB")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [44]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='str')

In [46]:
df.drop(columns=["mpg","cylinders"])

,displacement,horsepower,weight,acceleration,model year,origin,car name
0,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,350.0,165,3693,11.5,70,1,buick skylark 320
2,318.0,150,3436,11.0,70,1,plymouth satellite
3,304.0,150,3433,12.0,70,1,amc rebel sst
4,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...
393,140.0,86,2790,15.6,82,1,ford mustang gl
394,97.0,52,2130,24.6,82,2,vw pickup
395,135.0,84,2295,11.6,82,1,dodge rampage
396,120.0,79,2625,18.6,82,1,ford ranger
397,119.0,82,2720,19.4,82,1,chevy s-10

In [48]:
df=pd.read_csv("Datasets/heights_weights.csv")
os.chdir("D:/Yuvraj/LJ/LJ/PYTHON/PB")
df

         Height      Weight  Male
0     73.847017  241.893563     1
1     68.781904  162.310473     1
2     74.110105  212.740856     1
3     71.730978  220.042470     1
4     69.881796  206.349801     1
...         ...         ...   ...
9995  66.172652  136.777454     0
9996  67.067155  170.867906     0
9997  63.867992  128.475319     0
9998  69.034243  163.852461     0
9999  61.944246  113.649103     0

[10000 rows x 3 columns]

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Height  10000 non-null  float64
 1   Weight  10000 non-null  float64
 2   Male    10000 non-null  int64
dtypes: float64(2), int64(1)
memory usage: 234.5 KB

In [51]:
df.describe()

             Height        Weight          Male
count  10000.000000  10000.000000  10000.000000
mean      66.367560    161.440357      0.500000
std        3.847528     32.108439      0.500025
min       54.263133     64.700127      0.000000
25%       63.505620    135.818051      0.000000
50%       66.318070    161.212928      0.500000
75%       69.174262    187.169525      1.000000
max       78.998742    269.989699      1.000000

In [54]:
df.corr()

          Height    Weight      Male
Height  1.000000  0.924756  0.691072
Weight  0.924756  1.000000  0.796723
Male    0.691072  0.796723  1.000000

In [70]:
pd.plotting.parallel_coordinates??

Signature:
pd.plotting.parallel_coordinates(
    frame: 'DataFrame',
    class_column: 'str',
    cols: 'list[str] | None' = None,
    ax: 'Axes | None' = None,
    color: 'list[str] | tuple[str, ...] | None' = None,
    use_columns: 'bool' = False,
    xticks: 'list | tuple | None' = None,
    colormap: 'Colormap | str | None' = None,
    axvlines: 'bool' = True,
    axvlines_kwds: 'Mapping[str, Any] | None' = None,
    sort_labels: 'bool' = False,
    **kwargs,
) -> 'Axes'
Source:
@set_module("pandas.plotting")
def parallel_coordinates(
    frame: DataFrame,
    class_column: str,
    cols: list[str] | None = None,
    ax: Axes | None = None,
    color: list[str] | tuple[str, ...] | None = None,
    use_columns: bool = False,
    xticks: list | tuple | None = None,
    colormap: Colormap | str | None = None,
    axvlines: bool = True,
    axvlines_kwds: Mapping[str, Any] | None = None,
    sort_labels: bool = False,
    **kwargs,
) -> Axes:
    """
    Parallel coordinates plotting.

    Parameters
    ----------
    frame : DataFrame
        The DataFrame to be plotted.
    class_column : str
        Column name containing class names.
    cols : list, optional
        A list of column names to use.
    ax : matplotlib.axis, optional
        Matplotlib axis object.
    color : list or tuple, optional
        Colors to use for the different classes.
    use_columns : bool, optional
        If true, columns will be used as xticks.
    xticks : list or tuple, optional
        A list of values to use for xticks.
    colormap : str or matplotlib colormap, default None
        Colormap to use for line colors.
    axvlines : bool, optional
        If true, vertical lines will be added at each xtick.
    axvlines_kwds : keywords, optional
        Options to be passed to axvline method for vertical lines.
    sort_labels : bool, default False
        Sort class_column labels, useful when assigning colors.
    **kwargs
        Options to pass to matplotlib plotting method.

    Returns
    -------
    matplotlib.axes.Axes
        The matplotlib axes containing the parallel coordinates plot.

    See Also
    --------
    plotting.andrews_curves : Generate a matplotlib plot for visualizing clusters
        of multivariate data.
    plotting.radviz : Plot a multidimensional dataset in 2D.

    Examples
    --------

    .. plot::
        :context: close-figs

        >>> df = pd.read_csv(
        ...     "https://raw.githubusercontent.com/pandas-dev/"
        ...     "pandas/main/pandas/tests/io/data/csv/iris.csv"
        ... )  # doctest: +SKIP
        >>> pd.plotting.parallel_coordinates(
        ...     df, "Name", color=("#556270", "#4ECDC4", "#C7F464")
        ... )  # doctest: +SKIP
    """
    plot_backend = _get_plot_backend("matplotlib")
    return plot_backend.parallel_coordinates(
        frame=frame,
        class_column=class_column,
        cols=cols,
        ax=ax,
        color=color,
        use_columns=use_columns,
        xticks=xticks,
        colormap=colormap,
        axvlines=axvlines,
        axvlines_kwds=axvlines_kwds,
        sort_labels=sort_labels,
        **kwargs,
    )
File:      c:\users\yuvra\anaconda3\lib\site-packages\pandas\plotting\_misc.py
Type:      function

In [72]:
df=pd.read_csv("Datasets/auto-mpg.csv")
os.chdir("D:/Yuvraj/LJ/LJ/PYTHON/PB")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [76]:
df["horsepower"].unique

count     398
unique     94
top       150
freq       22
Name: horsepower, dtype: object