In [1]:
import pandas as pd
import numpy as np

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
df=pd.read_csv("PANDAS_DATA/social_media_engagement.csv")
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [5]:
df.apply(lambda x:"Good" if x["likes"]>=3000 else "Bad",axis=1)

0      Bad
1     Good
2     Good
3      Bad
4     Good
      ...
95     Bad
96     Bad
97     Bad
98    Good
99    Good
Length: 100, dtype: object

In [8]:
df["risk_level"]=df.apply(lambda x:'risk high' if ((x["likes"]>500) and (x["comments"]<100)) else ("medium" if (x["likes"])>2000 else ("low" if x["shares"]>1000 else "Undefined")),axis=1)

In [9]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score,risk_level
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive,medium
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral,medium
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative,medium
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative,risk high
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive,medium
...,...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive,Undefined
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral,Undefined
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive,Undefined
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive,medium
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral,medium

In [12]:
def more(x,grater,v=11):
    return x+grater+v
df["likes"].apply(more,args=(5,),v=10)

0     2136
1     3675
2     4970
3     1198
4     3514
      ...
95      51
96     329
97     244
98    5015
99    4498
Name: likes, Length: 100, dtype: int64

In [15]:
df.groupby("platform")

In [20]:
df.groupby("platform").head()

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score,risk_level
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive,medium
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral,medium
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative,medium
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative,risk high
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive,medium
5,6,Instagram,carousel,5/5/2023 20:00,256,186,211,Friday,neutral,Undefined
6,7,Instagram,image,2/26/2023 11:45,1982,30,906,Sunday,positive,risk high
7,8,Instagram,text,10/28/2023 19:30,1274,45,216,Saturday,neutral,risk high
8,9,Facebook,video,5/2/2023 6:15,317,249,221,Tuesday,neutral,Undefined
9,10,Twitter,carousel,5/11/2023 11:00,1878,225,438,Thursday,neutral,Undefined
10,11,Twitter,text,12/8/2023 2:15,1446,44,52,Friday,negative,risk high
11,12,Twitter,video,6/15/2023 3:15,304,42,89,Thursday,positive,Undefined
12,13,Facebook,carousel,11/11/2023 15:45,45,78,375,Saturday,negative,Undefined
14,15,Facebook,carousel,1/9/2023 20:00,889,314,262,Monday,positive,Undefined
16,17,Instagram,poll,7/5/2023 5:15,2872,10,736,Wednesday,positive,risk high

In [21]:
df["platform"].unique()

array(['Facebook', 'Instagram', 'Twitter'], dtype=object)

In [22]:
for name,data in df.groupby("platform"):
    print(name,data)

Facebook     post_id  platform post_type         post_time  likes  comments  shares  \
0         1  Facebook     image   8/17/2023 14:45   2121       474     628
1         2  Facebook  carousel    5/14/2023 0:45   3660       432     694
8         9  Facebook     video     5/2/2023 6:15    317       249     221
12       13  Facebook  carousel  11/11/2023 15:45     45        78     375
14       15  Facebook  carousel    1/9/2023 20:00    889       314     262
19       20  Facebook     image    2/2/2023 16:00    455        86      79
25       26  Facebook  carousel    10/5/2023 6:30   1992        70     515
27       28  Facebook      poll     3/1/2023 8:00   2083       500     388
28       29  Facebook     image    1/7/2023 10:30    548       153     731
29       30  Facebook  carousel     2/3/2023 0:30   4594       216     739
30       31  Facebook      poll   9/10/2023 13:45   4795       449     978
35       36  Facebook     video    4/8/2023 19:15   5000       500      43
36       37  Facebook     video    5/11/2023 0:30   4245        59      83
38       39  Facebook     video     1/1/2023 6:00   5000       430     980
46       47  Facebook      poll    8/8/2023 17:45   4726        44     993
47       48  Facebook     video    3/22/2023 3:15   5000       232      16
57       58  Facebook     video   12/27/2023 4:00   2204       116     728
61       62  Facebook  carousel   1/27/2023 15:45   3742       227     849
65       66  Facebook      text     1/3/2023 3:00   2265        39     318
66       67  Facebook  carousel    4/23/2023 8:15   2026       390     165
69       70  Facebook      text    6/12/2023 9:30   3094        86     965
71       72  Facebook  carousel    5/5/2023 16:45   1690       257     656
72       73  Facebook      text   7/18/2023 22:00   3026        11     761
74       75  Facebook     video   7/26/2023 20:15   5000       500     404
79       80  Facebook      text   6/25/2023 15:15    553       320     312
80       81  Facebook     video    1/4/2023 18:30   2642        33     413
83       84  Facebook  carousel   10/3/2023 19:00   1203       263     417
84       85  Facebook      text     7/6/2023 7:00   2566       368     304
87       88  Facebook      text    5/3/2023 12:30   3404       244      67
90       91  Facebook  carousel    9/15/2023 0:45   3956       402     462
91       92  Facebook     video   2/23/2023 17:15   1857       216     344
93       94  Facebook     image   11/27/2023 4:30   1694       207     290

     post_day sentiment_score risk_level
0    Thursday        positive     medium
1      Sunday         neutral     medium
8     Tuesday         neutral  Undefined
12   Saturday        negative  Undefined
14     Monday        positive  Undefined
19   Thursday        positive  Undefined
25   Thursday        negative  risk high
27  Wednesday         neutral     medium
28   Saturday        negative  Undefined
29     Friday        positive     medium
30     Sunday        negative     medium
35   Saturday        positive     medium
36   Thursday         neutral  risk high
38     Sunday         neutral     medium
46    Tuesday        negative  risk high
47  Wednesday        negative     medium
57  Wednesday         neutral     medium
61     Friday        negative     medium
65    Tuesday        positive  risk high
66     Sunday        negative     medium
69     Monday        negative  risk high
71     Friday         neutral  Undefined
72    Tuesday        positive  risk high
74  Wednesday        positive     medium
79     Sunday        positive  Undefined
80  Wednesday         neutral  risk high
83    Tuesday        negative  Undefined
84   Thursday         neutral     medium
87  Wednesday        positive     medium
90     Friday        negative     medium
91   Thursday        positive  Undefined
93     Monday        positive  Undefined
Instagram     post_id   platform post_type         post_time  likes  comments  shares  \
2         3  Instagram      poll   2/21/2023 16:15   4955       408     688
5         6  Instagram  carousel    5/5/2023 20:00    256       186     211
6         7  Instagram     image   2/26/2023 11:45   1982        30     906
7         8  Instagram      text  10/28/2023 19:30   1274        45     216
16       17  Instagram      poll     7/5/2023 5:15   2872        10     736
23       24  Instagram  carousel    1/1/2023 20:00   5000        80     399
26       27  Instagram      text   10/6/2023 10:00   3161       162     137
31       32  Instagram     image    7/1/2023 14:45   4665       202     183
34       35  Instagram     image    6/6/2023 19:30   1309       201     852
39       40  Instagram  carousel    8/4/2023 12:45    447       333     845
41       42  Instagram     video   11/23/2023 2:00   4929       252     730
43       44  Instagram      text     7/6/2023 8:00   3259        50     177
45       46  Instagram      text   5/16/2023 22:15   2251       380     427
49       50  Instagram      text    7/12/2023 0:00   1551       206     127
53       54  Instagram     image    1/21/2023 1:00   4297       360     825
55       56  Instagram     image   3/13/2023 23:15   3401       190     230
56       57  Instagram     video    7/13/2023 9:15   4846       134     498
59       60  Instagram  carousel    5/19/2023 4:30   4763       332     956
60       61  Instagram     video  12/31/2023 22:30   3544       167     761
63       64  Instagram  carousel   4/19/2023 19:45    130       452     724
64       65  Instagram     image    9/20/2023 6:00   3982       314     326
67       68  Instagram     video  12/28/2023 16:45    560       486     677
70       71  Instagram     video    4/10/2023 0:00   3398       261     630
73       74  Instagram     video   4/14/2023 10:30   5000       454     744
75       76  Instagram      text   7/27/2023 19:15   2153        81     114
77       78  Instagram      poll    1/19/2023 7:15   2990        30     365
78       79  Instagram  carousel   12/13/2023 4:45   4678       189     785
81       82  Instagram  carousel  11/19/2023 12:30   4656       314     757
82       83  Instagram     video    12/6/2023 4:00   5000       173     792
86       87  Instagram      text   5/23/2023 22:30     15        70     454
89       90  Instagram      poll    3/19/2023 4:00   3195       109     243
92       93  Instagram  carousel     5/7/2023 0:30    951       432     734
94       95  Instagram      poll    3/7/2023 19:15   3005       124     517
95       96  Instagram  carousel   7/12/2023 17:45     36       294     911
98       99  Instagram      poll  12/29/2023 12:15   5000       500     204
99      100  Instagram     image    6/6/2023 21:00   4483       357      25

     post_day sentiment_score risk_level
2     Tuesday        negative     medium
5      Friday         neutral  Undefined
6      Sunday        positive  risk high
7    Saturday         neutral  risk high
16  Wednesday        positive  risk high
23     Sunday        positive  risk high
26     Friday        positive     medium
31   Saturday        positive     medium
34    Tuesday        negative  Undefined
39     Friday        negative  Undefined
41   Thursday        negative     medium
43   Thursday        negative  risk high
45    Tuesday        positive     medium
49  Wednesday        negative  Undefined
53   Saturday        negative     medium
55     Monday        negative     medium
56   Thursday         neutral     medium
59     Friday        positive     medium
60     Sunday        negative     medium
63  Wednesday         neutral  Undefined
64  Wednesday        positive     medium
67   Thursday        negative  Undefined
70     Monday         neutral     medium
73     Friday        positive     medium
75   Thursday         neutral  risk high
77   Thursday        positive  risk high
78  Wednesday        positive     medium
81     Sunday        negative     medium
82  Wednesday        negative     medium
86    Tuesday         neutral  Undefined
89     Sunday        negative     medium
92     Sunday        negative  Undefined
94    Tuesday        positive     medium
95  Wednesday        positive  Undefined
98     Friday        positive     medium
99    Tuesday         neutral     medium
Twitter     post_id platform post_type         post_time  likes  comments  shares  \
3         4  Twitter     image   11/16/2023 0:45   1183        90     187
4         5  Twitter     video    5/23/2023 0:30   3499       247     286
9        10  Twitter  carousel   5/11/2023 11:00   1878       225     438
10       11  Twitter      text    12/8/2023 2:15   1446        44      52
11       12  Twitter     video    6/15/2023 3:15    304        42      89
13       14  Twitter      text   9/30/2023 10:30   1333       144     123
15       16  Twitter     image   2/10/2023 13:00   2348       154      18
17       18  Twitter      text    7/23/2023 5:45    512       123     338
18       19  Twitter      text   11/20/2023 2:00   2013       122     183
20       21  Twitter      poll     5/2/2023 6:15    559       136      55
21       22  Twitter  carousel   1/30/2023 13:30   1961        44     439
22       23  Twitter      text   10/2/2023 12:15    332       109     348
24       25  Twitter      poll    5/17/2023 0:15    898       130     480
32       33  Twitter     video   9/27/2023 19:00    119       147     240
33       34  Twitter      poll    2/9/2023 15:30   2253       162      28
37       38  Twitter      poll     5/2/2023 0:30   2463       187     445
40       41  Twitter  carousel  12/27/2023 11:30    667       176     461
42       43  Twitter  carousel   3/31/2023 16:00   2586        97      85
44       45  Twitter     video   12/1/2023 10:00   2236       132     118
48       49  Twitter     image   4/17/2023 15:00    725       169     298
50       51  Twitter      text   2/14/2023 18:00   1268        73     251
51       52  Twitter     image   7/14/2023 15:00    950       113     327
52       53  Twitter     video  11/12/2023 17:30   1498        46      96
54       55  Twitter  carousel   10/2/2023 23:30    592        34     496
58       59  Twitter     video   12/24/2023 7:45    344        99     194
62       63  Twitter     image    5/15/2023 6:30    227       163     127
68       69  Twitter     image  10/14/2023 18:45    187        89     284
76       77  Twitter  carousel    7/5/2023 18:15   3571       102      96
85       86  Twitter      text   11/25/2023 7:30   2416        50      62
88       89  Twitter  carousel     5/3/2023 8:00   2884       197     339
96       97  Twitter     video  10/27/2023 23:45    314       108     458
97       98  Twitter      text     8/5/2023 8:45    229       179      38

     post_day sentiment_score risk_level
3    Thursday        negative  risk high
4     Tuesday        positive     medium
9    Thursday         neutral  Undefined
10     Friday        negative  risk high
11   Thursday        positive  Undefined
13   Saturday        positive  Undefined
15     Friday         neutral     medium
17     Sunday         neutral  Undefined
18     Monday        positive     medium
20    Tuesday         neutral  Undefined
21     Monday        positive  risk high
22     Monday        positive  Undefined
24  Wednesday        positive  Undefined
32  Wednesday        positive  Undefined
33   Thursday        positive     medium
37    Tuesday        positive     medium
40  Wednesday        positive  Undefined
42     Friday        positive  risk high
44     Friday        positive     medium
48     Monday         neutral  Undefined
50    Tuesday        positive  risk high
51     Friday        positive  Undefined
52     Sunday        positive  risk high
54     Monday         neutral  risk high
58     Sunday         neutral  Undefined
62     Monday         neutral  Undefined
68   Saturday         neutral  Undefined
76  Wednesday        positive     medium
85   Saturday        positive  risk high
88  Wednesday        positive     medium
96     Friday         neutral  Undefined
97   Saturday        positive  Undefined

In [23]:
df.groupby("platform").sample()

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score,risk_level
30,31,Facebook,poll,9/10/2023 13:45,4795,449,978,Sunday,negative,medium
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral,medium
18,19,Twitter,text,11/20/2023 2:00,2013,122,183,Monday,positive,medium

In [24]:
df.groupby("platform").describe()

          post_id                                                       likes  \
            count       mean        std  min    25%   50%    75%    max count
platform
Facebook     32.0  51.531250  29.195652  1.0  28.75  53.0  76.25   94.0  32.0
Instagram    36.0  57.472222  28.866675  3.0  38.75  60.5  79.75  100.0  36.0
Twitter      32.0  41.625000  27.492814  4.0  18.75  39.5  56.00   98.0  32.0

                        ... comments        shares                          \
                  mean  ...      75%    max  count        mean         std
platform                ...
Facebook   2699.750000  ...   393.00  500.0   32.0  474.375000  299.739430
Instagram  2999.833333  ...   339.00  500.0   36.0  525.166667  284.467472
Twitter    1368.593750  ...   162.25  247.0   32.0  233.718750  156.508525


            min     25%    50%     75%    max
platform
Facebook   16.0  283.00  408.5  728.75  993.0
Instagram  25.0  226.50  573.5  758.00  956.0
Twitter    18.0   94.25  217.0  341.25  496.0

[3 rows x 32 columns]

In [26]:
df.groupby("platform").groups

{'Facebook': [0, 1, 8, 12, 14, 19, 25, 27, 28, 29, 30, 35, 36, 38, 46, 47, 57, 61, 65, 66, 69, 71, 72, 74, 79, 80, 83, 84, 87, 90, 91, 93], 'Instagram': [2, 5, 6, 7, 16, 23, 26, 31, 34, 39, 41, 43, 45, 49, 53, 55, 56, 59, 60, 63, 64, 67, 70, 73, 75, 77, 78, 81, 82, 86, 89, 92, 94, 95, 98, 99], 'Twitter': [3, 4, 9, 10, 11, 13, 15, 17, 18, 20, 21, 22, 24, 32, 33, 37, 40, 42, 44, 48, 50, 51, 52, 54, 58, 62, 68, 76, 85, 88, 96, 97]}

In [29]:
df.platform.unique()

array(['Facebook', 'Instagram', 'Twitter'], dtype=object)

In [30]:
df.groupby("platform").nunique()

,post_id,post_type,post_time,likes,comments,shares,post_day,sentiment_score,risk_level
platform,,,,,,,,,
Facebook,32,5,32,29,28,32,7,3,3
Instagram,36,5,36,33,34,36,7,3,3
Twitter,32,5,32,32,31,31,7,3,3

In [31]:
df.groupby("platform")["likes"].sum()

platform
Facebook      86392
Instagram    107994
Twitter       43795
Name: likes, dtype: int64

In [33]:
df.groupby("platform")["comments"].sum()

platform
Facebook     7965
Instagram    8368
Twitter      3933
Name: comments, dtype: int64

In [34]:
df.groupby("platform",as_index=False)["likes"].sum()

    platform   likes
0   Facebook   86392
1  Instagram  107994
2    Twitter   43795

In [35]:
df.groupby("platform",as_index=True)["likes"].sum()

platform
Facebook      86392
Instagram    107994
Twitter       43795
Name: likes, dtype: int64

In [39]:
df.groupby("platform",as_index=False)[["likes","comments","shares"]].mean()

    platform        likes    comments      shares
0   Facebook  2699.750000  248.906250  474.375000
1  Instagram  2999.833333  232.444444  525.166667
2    Twitter  1368.593750  122.906250  233.718750

In [42]:
df.groupby("platform",as_index=False).agg({"likes":[sum,"mean"],"comments":"mean"})

    platform   likes                 comments
                 sum         mean        mean
0   Facebook   86392  2699.750000  248.906250
1  Instagram  107994  2999.833333  232.444444
2    Twitter   43795  1368.593750  122.906250

In [43]:
df.groupby("platform",as_index=False).apply(sum)

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score,risk_level
0,1649,FacebookFacebookFacebookFacebookFacebookFacebo...,imagecarouselvideocarouselcarouselimagecarouse...,8/17/2023 14:455/14/2023 0:455/2/2023 6:1511/1...,86392,7965,15180,ThursdaySundayTuesdaySaturdayMondayThursdayThu...,positiveneutralneutralnegativepositivepositive...,mediummediumUndefinedUndefinedUndefinedUndefin...
1,2069,InstagramInstagramInstagramInstagramInstagramI...,pollcarouselimagetextpollcarouseltextimageimag...,2/21/2023 16:155/5/2023 20:002/26/2023 11:4510...,107994,8368,18906,TuesdayFridaySundaySaturdayWednesdaySundayFrid...,negativeneutralpositiveneutralpositivepositive...,mediumUndefinedrisk highrisk highrisk highrisk...
2,1332,TwitterTwitterTwitterTwitterTwitterTwitterTwit...,imagevideocarouseltextvideotextimagetexttextpo...,11/16/2023 0:455/23/2023 0:305/11/2023 11:0012...,43795,3933,7479,ThursdayTuesdayThursdayFridayThursdaySaturdayF...,negativepositiveneutralnegativepositivepositiv...,risk highmediumUndefinedrisk highUndefinedUnde...

In [44]:
df.groupby("platform").nth(0)

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score,risk_level
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive,medium
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative,medium
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative,risk high

In [ ]:
df.groupby("platform")