In [1]:
import pandas as pd
import numpy as np

In [5]:
ds=pd.Series([10,20,30,40])
print(ds)
ds

0    10
1    20
2    30
3    40
dtype: int64

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
ds=pd.Series((10,20,30,40))
print(ds)
ds

0    10
1    20
2    30
3    40
dtype: int64

0    10
1    20
2    30
3    40
dtype: int64

In [7]:
ds=pd.Series({10:1,20:2,30:3,40:4})
print(ds)
ds

10    1
20    2
30    3
40    4
dtype: int64

10    1
20    2
30    3
40    4
dtype: int64

In [8]:
ds=pd.Series([10,20,30,40],index=['A','B','C','D'])
print(ds)
ds

A    10
B    20
C    30
D    40
dtype: int64

A    10
B    20
C    30
D    40
dtype: int64

In [10]:
ds=pd.Series({10:1,20:2,30:3,40:4},index=['A','B','C','D'])
print(ds)
ds

A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64

A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64

In [12]:
ds=pd.Series([x for x in range(11)])
print(ds)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [14]:
ds=pd.Series([x for x in range(11)],index=[x for x in range(1,12)])
print(ds)

1      0
2      1
3      2
4      3
5      4
6      5
7      6
8      7
9      8
10     9
11    10
dtype: int64

In [17]:
type(ds)

pandas.core.series.Series

In [19]:
ds=pd.DataFrame([['V','H','A'],[10,20,30],[1,2,3]],index=['A','B',"C"],columns=["P","Q","R"])
print(ds)

    P   Q   R
A   V   H   A
B  10  20  30
C   1   2   3

In [20]:
ds=pd.DataFrame({10:1,20:2,30:3,40:4},index=['A','B',"C"])
print(ds)

   10  20  30  40
A   1   2   3   4
B   1   2   3   4
C   1   2   3   4

In [21]:
ds=pd.DataFrame({'P':['V','H','A'],'Q':[10,20,30],'R':[1,2,3]},index=['A','B',"C"])
print(ds)

   P   Q  R
A  V  10  1
B  H  20  2
C  A  30  3

In [22]:
ds=pd.DataFrame({'P':['V','H','A'],'Q':[10,20,30],'R':[1,2,3]})
print(ds)

   P   Q  R
0  V  10  1
1  H  20  2
2  A  30  3

In [23]:
ds=pd.DataFrame({'P':['V','H','A'],'Q':[10,20,30],'R':[1,2,3]},index=['A','B',"C"],columns=["X","Y","Z"])
print(ds)

     X    Y    Z
A  NaN  NaN  NaN
B  NaN  NaN  NaN
C  NaN  NaN  NaN

In [24]:
ds=pd.DataFrame({'P':['V','H','A'],'Q':[10,20,30],'R':[1,2,3]},index=['A','B',"C"],columns=["X","Y","R"])#It find from dict.
print(ds)

     X    Y  R
A  NaN  NaN  1
B  NaN  NaN  2
C  NaN  NaN  3

In [25]:
ds=pd.DataFrame(np.array([10,20,30,40]))
print(ds)

    0
0  10
1  20
2  30
3  40

In [27]:
ds=pd.DataFrame({10:1,20:2,30:3,40:4})
print(ds)

ValueError: If using all scalar values, you must pass an index

In [28]:
ds=pd.DataFrame([{'A':['a','1b','c'],1:[1,2,3]},{'A':['a','2b','c'],1:[1,2,3]},{'A':['a','3b','c'],1:[1,2,3]}],index=['x','y','z'])
ds

            A          1
x  [a, 1b, c]  [1, 2, 3]
y  [a, 2b, c]  [1, 2, 3]
z  [a, 3b, c]  [1, 2, 3]

In [31]:
df=pd.DataFrame({"Sub":["Python","FSD","COA","TOC","DM"],"Fac":["VHA","PSP","VBY","DPS","MSS"],"Mark":[10,9,10,9,9]})
df

      Sub  Fac  Mark
0  Python  VHA    10
1     FSD  PSP     9
2     COA  VBY    10
3     TOC  DPS     9
4      DM  MSS     9

In [32]:
df.set_index('Sub')

        Fac  Mark
Sub
Python  VHA    10
FSD     PSP     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [33]:
df.set_index('Sub',drop=True)

        Fac  Mark
Sub
Python  VHA    10
FSD     PSP     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [34]:
df.set_index('Sub',drop=False)

           Sub  Fac  Mark
Sub
Python  Python  VHA    10
FSD        FSD  PSP     9
COA        COA  VBY    10
TOC        TOC  DPS     9
DM          DM  MSS     9

In [35]:
df

      Sub  Fac  Mark
0  Python  VHA    10
1     FSD  PSP     9
2     COA  VBY    10
3     TOC  DPS     9
4      DM  MSS     9

In [37]:
df=df.set_index('Sub',drop=True)

In [38]:
df

        Fac  Mark
Sub
Python  VHA    10
FSD     PSP     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [39]:
df=df.reset_index()

In [40]:
df

      Sub  Fac  Mark
0  Python  VHA    10
1     FSD  PSP     9
2     COA  VBY    10
3     TOC  DPS     9
4      DM  MSS     9

In [41]:
df=pd.DataFrame({"Sub":["Python","FSD","COA","TOC","DM"],"Fac":["VHA","PSP","VBY","DPS","MSS"],"Mark":[10,9,10,9,9]})
df

      Sub  Fac  Mark
0  Python  VHA    10
1     FSD  PSP     9
2     COA  VBY    10
3     TOC  DPS     9
4      DM  MSS     9

In [42]:
df=df.set_index("Sub")
df

        Fac  Mark
Sub
Python  VHA    10
FSD     PSP     9
COA     VBY    10
TOC     DPS     9
DM      MSS     9

In [43]:
df.loc['FSD',"Fac"]

'PSP'

In [44]:
df.loc['FSD','Fac']="NAS"

In [45]:
df.loc['FSD',"Fac"]

'NAS'

In [47]:
df.loc["Fac",'FSD']

KeyError: 'Fac'

In [48]:
df.loc['FSD','Mark']=10
df.loc['FSD']

Fac     NAS
Mark     10
Name: FSD, dtype: object

In [49]:
df.loc['Project']=['VHA',10]

In [50]:
df

         Fac  Mark
Sub
Python   VHA    10
FSD      NAS    10
COA      VBY    10
TOC      DPS     9
DM       MSS     9
Project  VHA    10

In [51]:
df['HOD']="MJT"

In [52]:
df

         Fac  Mark  HOD
Sub
Python   VHA    10  MJT
FSD      NAS    10  MJT
COA      VBY    10  MJT
TOC      DPS     9  MJT
DM       MSS     9  MJT
Project  VHA    10  MJT

In [53]:
df['New']=df['Mark']*10
df

         Fac  Mark  HOD  New
Sub
Python   VHA    10  MJT  100
FSD      NAS    10  MJT  100
COA      VBY    10  MJT  100
TOC      DPS     9  MJT   90
DM       MSS     9  MJT   90
Project  VHA    10  MJT  100