In [1]:
import pandas as pd
import numpy as np

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df=pd.DataFrame(np.random.randint(1,100,(20,5)),columns=["A","B","C","D","E"])

In [3]:
df

     A   B   C   D   E
0   83  87  41  84  93
1   56   6  18  44  29
2   41  13  93  83  63
3   23  31  71  48  63
4   99  65  96  65   8
5   44   9  40  99  67
6   36  27  24  35  52
7   10  90  49  76  68
8   62  88  55  12  69
9   16  84  50  67  68
10   7  14  87  91  43
11  96  77  73  41  49
12  73  14  12  14   3
13  30  16  17  80  23
14  12  80  10  10  88
15  58  84  21  20  29
16  93  85  19  89  47
17  78  53  55  76  15
18  93  57  11  61  54
19  92  17  53  96  99

In [4]:
df.apply(sum)

A    1102
B     997
C     895
D    1191
E    1030
dtype: int64

In [5]:
df.apply(sum,axis=1)

0     388
1     153
2     293
3     236
4     333
5     259
6     174
7     293
8     286
9     285
10    242
11    336
12    116
13    166
14    200
15    212
16    333
17    277
18    276
19    357
dtype: int64

TypeError: 'int' object is not iterable

In [7]:
df.apply("mean")

A    55.10
B    49.85
C    44.75
D    59.55
E    51.50
dtype: float64

In [8]:
df.apply(lambda x:x["A"]+x["B"]+x["C"],axis=1)

0     211
1      80
2     147
3     125
4     260
5      93
6      87
7     149
8     205
9     150
10    108
11    246
12     99
13     63
14    102
15    163
16    197
17    186
18    161
19    162
dtype: int32

In [9]:
df["Total"]=df.apply(sum,axis=1)
df

     A   B   C   D   E  Total
0   83  87  41  84  93    388
1   56   6  18  44  29    153
2   41  13  93  83  63    293
3   23  31  71  48  63    236
4   99  65  96  65   8    333
5   44   9  40  99  67    259
6   36  27  24  35  52    174
7   10  90  49  76  68    293
8   62  88  55  12  69    286
9   16  84  50  67  68    285
10   7  14  87  91  43    242
11  96  77  73  41  49    336
12  73  14  12  14   3    116
13  30  16  17  80  23    166
14  12  80  10  10  88    200
15  58  84  21  20  29    212
16  93  85  19  89  47    333
17  78  53  55  76  15    277
18  93  57  11  61  54    276
19  92  17  53  96  99    357

In [12]:
df["Grade"]=df.apply(lambda x:"A" if x["Total"]>300 else ("B" if x["Total"]>200 else "C"),axis=1)
df

     A   B   C   D   E  Total Grade
0   83  87  41  84  93    388     A
1   56   6  18  44  29    153     C
2   41  13  93  83  63    293     B
3   23  31  71  48  63    236     B
4   99  65  96  65   8    333     A
5   44   9  40  99  67    259     B
6   36  27  24  35  52    174     C
7   10  90  49  76  68    293     B
8   62  88  55  12  69    286     B
9   16  84  50  67  68    285     B
10   7  14  87  91  43    242     B
11  96  77  73  41  49    336     A
12  73  14  12  14   3    116     C
13  30  16  17  80  23    166     C
14  12  80  10  10  88    200     C
15  58  84  21  20  29    212     B
16  93  85  19  89  47    333     A
17  78  53  55  76  15    277     B
18  93  57  11  61  54    276     B
19  92  17  53  96  99    357     A

In [15]:
def grade(x):
    if x>300:
        return "A+"
    if x>200:
        return "A"
    if x>100:
        return "B"
    return "F"
df["GradeUsin.apply"]=df["Total"].apply(grade);
df

     A   B   C   D   E  Total Grade GradeUsin.apply
0   83  87  41  84  93    388     A              A+
1   56   6  18  44  29    153     C               B
2   41  13  93  83  63    293     B               A
3   23  31  71  48  63    236     B               A
4   99  65  96  65   8    333     A              A+
5   44   9  40  99  67    259     B               A
6   36  27  24  35  52    174     C               B
7   10  90  49  76  68    293     B               A
8   62  88  55  12  69    286     B               A
9   16  84  50  67  68    285     B               A
10   7  14  87  91  43    242     B               A
11  96  77  73  41  49    336     A              A+
12  73  14  12  14   3    116     C               B
13  30  16  17  80  23    166     C               B
14  12  80  10  10  88    200     C               B
15  58  84  21  20  29    212     B               A
16  93  85  19  89  47    333     A              A+
17  78  53  55  76  15    277     B               A
18  93  57  11  61  54    276     B               A
19  92  17  53  96  99    357     A              A+

In [24]:
df["Indiviadual"]=df.apply(lambda x:"Fail" if ((x["A"]<35) or (x["B"]<35) or (x["C"]<35) or (x["D"]<35) or (x["E"]<35)) else "Pass",axis=1)
df

     A   B   C   D   E  Total Grade GradeUsin.apply Indiviadual
0   83  87  41  84  93    388     A              A+        Pass
1   56   6  18  44  29    153     C               B        Fail
2   41  13  93  83  63    293     B               A        Fail
3   23  31  71  48  63    236     B               A        Fail
4   99  65  96  65   8    333     A              A+        Fail
5   44   9  40  99  67    259     B               A        Fail
6   36  27  24  35  52    174     C               B        Fail
7   10  90  49  76  68    293     B               A        Fail
8   62  88  55  12  69    286     B               A        Fail
9   16  84  50  67  68    285     B               A        Fail
10   7  14  87  91  43    242     B               A        Fail
11  96  77  73  41  49    336     A              A+        Pass
12  73  14  12  14   3    116     C               B        Fail
13  30  16  17  80  23    166     C               B        Fail
14  12  80  10  10  88    200     C               B        Fail
15  58  84  21  20  29    212     B               A        Fail
16  93  85  19  89  47    333     A              A+        Fail
17  78  53  55  76  15    277     B               A        Fail
18  93  57  11  61  54    276     B               A        Fail
19  92  17  53  96  99    357     A              A+        Fail

In [27]:
def res(x):
    if (x["A"]<35) or (x["B"]<35) or (x["C"]<35) or (x["D"]<35) or (x["E"]<35):
        return "Fail"
    return "Pass"
df.apply(res,axis=1)

0     Pass
1     Fail
2     Fail
3     Fail
4     Fail
5     Fail
6     Fail
7     Fail
8     Fail
9     Fail
10    Fail
11    Pass
12    Fail
13    Fail
14    Fail
15    Fail
16    Fail
17    Fail
18    Fail
19    Fail
dtype: object

In [25]:
df["Percentage"]=df.apply(lambda x:x["Total"]*0.2,axis=1)
df

     A   B   C   D   E  Total Grade GradeUsin.apply Indiviadual  Percentage
0   83  87  41  84  93    388     A              A+        Pass        77.6
1   56   6  18  44  29    153     C               B        Fail        30.6
2   41  13  93  83  63    293     B               A        Fail        58.6
3   23  31  71  48  63    236     B               A        Fail        47.2
4   99  65  96  65   8    333     A              A+        Fail        66.6
5   44   9  40  99  67    259     B               A        Fail        51.8
6   36  27  24  35  52    174     C               B        Fail        34.8
7   10  90  49  76  68    293     B               A        Fail        58.6
8   62  88  55  12  69    286     B               A        Fail        57.2
9   16  84  50  67  68    285     B               A        Fail        57.0
10   7  14  87  91  43    242     B               A        Fail        48.4
11  96  77  73  41  49    336     A              A+        Pass        67.2
12  73  14  12  14   3    116     C               B        Fail        23.2
13  30  16  17  80  23    166     C               B        Fail        33.2
14  12  80  10  10  88    200     C               B        Fail        40.0
15  58  84  21  20  29    212     B               A        Fail        42.4
16  93  85  19  89  47    333     A              A+        Fail        66.6
17  78  53  55  76  15    277     B               A        Fail        55.4
18  93  57  11  61  54    276     B               A        Fail        55.2
19  92  17  53  96  99    357     A              A+        Fail        71.4

In [26]:
df["Result"]=df.apply(lambda x:"Fail" if x["Percentage"]<35.0 else "Pass",axis=1)
df

,A,B,C,D,E,Total,Grade,GradeUsin.apply,Indiviadual,Percentage,Result
0,83,87,41,84,93,388,A,A+,Pass,77.6,Pass
1,56,6,18,44,29,153,C,B,Fail,30.6,Fail
2,41,13,93,83,63,293,B,A,Fail,58.6,Pass
3,23,31,71,48,63,236,B,A,Fail,47.2,Pass
4,99,65,96,65,8,333,A,A+,Fail,66.6,Pass
5,44,9,40,99,67,259,B,A,Fail,51.8,Pass
6,36,27,24,35,52,174,C,B,Fail,34.8,Fail
7,10,90,49,76,68,293,B,A,Fail,58.6,Pass
8,62,88,55,12,69,286,B,A,Fail,57.2,Pass
9,16,84,50,67,68,285,B,A,Fail,57.0,Pass
10,7,14,87,91,43,242,B,A,Fail,48.4,Pass
11,96,77,73,41,49,336,A,A+,Pass,67.2,Pass
12,73,14,12,14,3,116,C,B,Fail,23.2,Fail
13,30,16,17,80,23,166,C,B,Fail,33.2,Fail
14,12,80,10,10,88,200,C,B,Fail,40.0,Pass
15,58,84,21,20,29,212,B,A,Fail,42.4,Pass
16,93,85,19,89,47,333,A,A+,Fail,66.6,Pass
17,78,53,55,76,15,277,B,A,Fail,55.4,Pass
18,93,57,11,61,54,276,B,A,Fail,55.2,Pass
19,92,17,53,96,99,357,A,A+,Fail,71.4,Pass

In [28]:
def bonus(y):
    return y+2

In [29]:
df["A"].apply(bonus)

0      85
1      58
2      43
3      25
4     101
5      46
6      38
7      12
8      64
9      18
10      9
11     98
12     75
13     32
14     14
15     60
16     95
17     80
18     95
19     94
Name: A, dtype: int64