In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Datasets/train.csv")

In [4]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Begin from here after coming from UNIT1_2

In [5]:
df=pd.DataFrame([[1,np.nan,3,4],[2,3,np.nan,8],[np.nan,4,5,9],[np.nan,1,np.nan,3],[np.nan,np.nan,np.nan,np.nan],[1,2,3,4]],columns=["A","B","C","D"])
df

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  3.0  NaN  8.0
2  NaN  4.0  5.0  9.0
3  NaN  1.0  NaN  3.0
4  NaN  NaN  NaN  NaN
5  1.0  2.0  3.0  4.0

In [6]:
df.fillna(df.mean())

          A    B         C    D
0  1.000000  2.5  3.000000  4.0
1  2.000000  3.0  3.666667  8.0
2  1.333333  4.0  5.000000  9.0
3  1.333333  1.0  3.666667  3.0
4  1.333333  2.5  3.666667  5.6
5  1.000000  2.0  3.000000  4.0

In [16]:
df["A"]=df["A"].fillna(df.A.mean)

In [17]:
df

                                                   A    B    C    D
0                                                  1  NaN  3.0  4.0
1                                                  2  3.0  NaN  8.0
2  <bound method Series.mean of 0    1.0\n1    2....  4.0  5.0  9.0
3  <bound method Series.mean of 0    1.0\n1    2....  1.0  NaN  3.0
4  <bound method Series.mean of 0    1.0\n1    2....  NaN  NaN  NaN
5                                                  1  2.0  3.0  4.0