### Create DataFrame from NumPy array 8,5

In [2]:
import numpy as np
import pandas as pd

In [31]:
x=np.array(np.random.randint(1,100,(8,5)))
x

array([[91, 34, 15, 33, 73],
       [47, 82, 61,  9, 49],
       [57, 10, 25, 25, 74],
       [31, 61, 84, 38, 96],
       [59, 41, 41, 87, 16],
       [80, 61, 54, 79, 26],
       [65,  3, 91,  2, 45],
       [82, 84, 27, 72, 89]])

In [32]:
df=pd.DataFrame(x,columns=['A','B','C','D','E'],index=[i for i in range(1,9)])

In [33]:
df

    A   B   C   D   E
1  91  34  15  33  73
2  47  82  61   9  49
3  57  10  25  25  74
4  31  61  84  38  96
5  59  41  41  87  16
6  80  61  54  79  26
7  65   3  91   2  45
8  82  84  27  72  89

In [34]:
df.shape

(8, 5)

In [35]:
df.size

40

In [36]:
df.ndim

2

In [37]:
df['Sum']=df['A']+df['B']+df['C']+df['D']+df['E']
df

    A   B   C   D   E  Sum
1  91  34  15  33  73  246
2  47  82  61   9  49  248
3  57  10  25  25  74  191
4  31  61  84  38  96  310
5  59  41  41  87  16  244
6  80  61  54  79  26  300
7  65   3  91   2  45  206
8  82  84  27  72  89  354

In [38]:
df.loc[6,'C']=32
df

    A   B   C   D   E  Sum
1  91  34  15  33  73  246
2  47  82  61   9  49  248
3  57  10  25  25  74  191
4  31  61  84  38  96  310
5  59  41  41  87  16  244
6  80  61  32  79  26  300
7  65   3  91   2  45  206
8  82  84  27  72  89  354

In [40]:
df.loc[2:7,'B':'D']

    B   C   D
2  82  61   9
3  10  25  25
4  61  84  38
5  41  41  87
6  61  32  79
7   3  91   2

In [41]:
df.loc[9]=[65, 5, 28, 46, 83,17]
df

ValueError: cannot set a row with mismatched columns