In [1]:
In a customer dataset, you have a column representing customer incomes. You want to categorize incomes into 'Low', 'Medium', 
and 'High' groups. Incomes below 30000 are 'Low', incomes between 30000 and 70000 are 'Medium', and incomes above 70000 
are 'High'. Write a code to achieve this assuming the dataset has a column named 'income'.

SyntaxError: invalid syntax (3111655098.py, line 1)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame({"income":[10000,70000,0000,50000,100000]})
df

   income
0   10000
1   70000
2   30000
3   50000
4  100000

In [9]:
df["Category"]=np.where(df["income"]<30000,"low",np.where((df["income"]>=30000) & (df["income"]<70000),"Medium","High"))

In [10]:
df

   income Category
0   10000      low
1   70000     High
2   30000   Medium
3   50000   Medium
4  100000     High

In [11]:
#  In a survey dataset, you have a column representing participants' ages. You want to categorize ages into 'Young', 'Middle-aged', 
# and 'Elderly' groups. Ages below 30 are 'Young', ages between 30 and 60 are 'Middle-aged', and ages above 60 are 'Elderly'. 
# Write a code to achieve this assuming the dataset has a column named 'age'.

SyntaxError: unterminated string literal (detected at line 1) (1489217747.py, line 1)

In [14]:
df=pd.DataFrame({"age":[10,20,40,22,60,80,11,np.nan]})
df

    age
0  10.0
1  20.0
2  40.0
3  22.0
4  60.0
5  80.0
6  11.0
7   NaN

In [15]:
df["categ"]=np.where(df["age"]<30,"young",np.where((df["age"]>=30) & (df["age"]<70),"middle-age","Elderly"))
df

    age       categ
0  10.0       young
1  20.0       young
2  40.0  middle-age
3  22.0       young
4  60.0  middle-age
5  80.0     Elderly
6  11.0       young
7   NaN     Elderly

In [16]:
# You've been given a dataset with apartment area and price information. There's a noticeable non-linear relationship between 
# area and price. To address this you intend to categorize them into 'High', 'Medium', and 'Low' groups. Prices above $3,000,000 
# are 'High', below $2,000,000 are 'Low', and between $2,000,000 and $3,000,000 are 'Medium'. Write a code to achieve this 
# assuming that dataset has two columns named area and price.

In [17]:
data = {
    "area": [850, 900, 1200, 1500, 1800, 2000, 2200, 2500],
    "price": [1500000, 2100000, 2800000, 3200000, 1900000, 3500000, 2400000, 4100000]
}
df = pd.DataFrame(data)

print(df)

   area    price
0   850  1500000
1   900  2100000
2  1200  2800000
3  1500  3200000
4  1800  1900000
5  2000  3500000
6  2200  2400000
7  2500  4100000

In [18]:
df["cat"]=np.where(df["price"]>3000000,"High",np.where(df["price"]<2000000,"Low","Medium"))

In [19]:
df

   area    price     cat
0   850  1500000     Low
1   900  2100000  Medium
2  1200  2800000  Medium
3  1500  3200000    High
4  1800  1900000     Low
5  2000  3500000    High
6  2200  2400000  Medium
7  2500  4100000    High

In [20]:
import pandas as pd
df = pd.DataFrame({
    "Dept":["IT","IT","HR","HR","Finance","Finance"],
    "Employee":["A","B","C","D","E","F"],
    "Experience":[2,5,3,7,4,6]
})
# Find the number of employees per department using size().
# Find the employee with highest experience in each department using nth() or sorting.
# Display results.
df

      Dept Employee  Experience
0       IT        A           2
1       IT        B           5
2       HR        C           3
3       HR        D           7
4  Finance        E           4
5  Finance        F           6

In [57]:
df.sort_values("Experience",ascending=False).groupby("Dept").nth(0)

      Dept Employee  Experience
3       HR        D           7
5  Finance        F           6
1       IT        B           5

In [21]:
df.groupby("Dept").size()

Dept
Finance    2
HR         2
IT         2
dtype: int64

In [55]:
df.groupby(["Dept"])["Experience"].describe()

         count  mean       std  min  25%  50%  75%  max
Dept
Finance    2.0   5.0  1.414214  4.0  4.5  5.0  5.5  6.0
HR         2.0   5.0  2.828427  3.0  4.0  5.0  6.0  7.0
IT         3.0   4.0  1.732051  2.0  3.5  5.0  5.0  5.0

In [58]:
import pandas as pd
df = pd.DataFrame({
    "Employee":["A","B","C","D","E"],
    "Dept":["IT","HR","IT","Finance","HR"],
    "Salary":[50000,40000,70000,80000,45000]
})
# Group employees by Department.
# Calculate total salary and average salary per department.
# Display departments where average salary is greater than 50,000.

In [74]:
x=df.groupby("Dept")["Salary"].agg(["sum","mean"])

In [75]:
x[x["mean"] > 50000

            sum     mean
Dept
Finance   80000  80000.0
IT       120000  60000.0

In [78]:
import pandas as pd
df = pd.DataFrame({
    "Product":["P1","P2","P3","P4","P5"],
    "Price":[100,200,150,300,250],
    "Quantity":[5,2,4,1,3]
})
# Create a new column TotalAmount = Price × Quantity using apply() row-wise.
# Sort the DataFrame by TotalAmount in descending order.

In [79]:
df["TotalAmount"]=

  Product  Price  Quantity
0      P1    100         5
1      P2    200         2
2      P3    150         4
3      P4    300         1
4      P5    250         3