In [1]:
import plotly

In [2]:
import numpy as np
import pandas as pd

C:\Users\LJENG\AppData\Roaming\Python\Python38\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [5]:
df1=pd.DataFrame({"A":[1,2],"B":[3,4]})
df2=pd.DataFrame({"A":[5,6],"B":[7,8]})

In [6]:
pd.concat(df1,df2)

TypeError: concat() takes 1 positional argument but 2 were given

In [7]:
pd.concat((df1,df2))

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [8]:
pd.concat((df1,df2),axis=0)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [9]:
pd.concat((df1,df2),axis=1)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [10]:
pd.concat((df1,df2),axis=0,ignore_index=True)

   A  B
0  1  3
1  2  4
2  5  7
3  6  8

In [11]:
pd.concat((df1,df2),axis=0,ignore_index=False,keys=["df1","df2"])

       A  B
df1 0  1  3
    1  2  4
df2 0  5  7
    1  6  8

In [12]:
df3=pd.DataFrame({"A":[1,2],"B":[3,4]})
df4=pd.DataFrame({"C":[5,6],"B":[7,8]})

In [14]:
pd.concat((df3,df4))

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [15]:
pd.concat((df3,df4),axis=1)

   A  B  C  B
0  1  3  5  7
1  2  4  6  8

In [16]:
df5=pd.DataFrame({"A":[1,2,3],"B":[3,4,5]})
df6=pd.DataFrame({"C":[5,6],"B":[7,8]})

In [18]:
pd.concat((df5,df6))

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
2  3.0  5  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [19]:
pd.concat((df5,df6),axis=1)

   A  B    C    B
0  1  3  5.0  7.0
1  2  4  6.0  8.0
2  3  5  NaN  NaN

In [20]:
pd.concat((df5,df6),join="inner")

   B
0  3
1  4
2  5
0  7
1  8

In [21]:
pd.concat((df5,df6),join="outer")

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
2  3.0  5  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [22]:
pd.concat((df3,df4),sort=True)

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  7  5.0
1  NaN  8  6.0

In [24]:
df1=pd.DataFrame({"name":["vha","psp","vby","mss","dps"],"sub":["python","fsd","coa","dm","toc"],"id":[3,2,1,4,6]})
df2=pd.DataFrame({"id":[1,2,3,4,5],"mark":[9,8,10,8,8]})

In [25]:
df1

  name     sub  id
0  vha  python   3
1  psp     fsd   2
2  vby     coa   1
3  mss      dm   4
4  dps     toc   6

In [26]:
df2

   id  mark
0   1     9
1   2     8
2   3    10
3   4     8
4   5     8

In [27]:
pd.merge(df1,df2,on="id")

  name     sub  id  mark
0  vha  python   3    10
1  psp     fsd   2     8
2  vby     coa   1     9
3  mss      dm   4     8

In [28]:
pd.merge(df1,df2,on="id",how="inner")

  name     sub  id  mark
0  vha  python   3    10
1  psp     fsd   2     8
2  vby     coa   1     9
3  mss      dm   4     8

In [30]:
pd.merge(df1,df2,on="id",how="outer")

  name     sub  id  mark
0  vha  python   3  10.0
1  psp     fsd   2   8.0
2  vby     coa   1   9.0
3  mss      dm   4   8.0
4  dps     toc   6   NaN
5  NaN     NaN   5   8.0

In [32]:
pd.merge(df1,df2,on="id",how="left")

  name     sub  id  mark
0  vha  python   3  10.0
1  psp     fsd   2   8.0
2  vby     coa   1   9.0
3  mss      dm   4   8.0
4  dps     toc   6   NaN

In [33]:
pd.merge(df1,df2,on="id",how="right")

  name     sub  id  mark
0  vby     coa   1     9
1  psp     fsd   2     8
2  vha  python   3    10
3  mss      dm   4     8
4  NaN     NaN   5     8

In [34]:
pd.merge(df1,df2,how="cross")

   name     sub  id_x  id_y  mark
0   vha  python     3     1     9
1   vha  python     3     2     8
2   vha  python     3     3    10
3   vha  python     3     4     8
4   vha  python     3     5     8
5   psp     fsd     2     1     9
6   psp     fsd     2     2     8
7   psp     fsd     2     3    10
8   psp     fsd     2     4     8
9   psp     fsd     2     5     8
10  vby     coa     1     1     9
11  vby     coa     1     2     8
12  vby     coa     1     3    10
13  vby     coa     1     4     8
14  vby     coa     1     5     8
15  mss      dm     4     1     9
16  mss      dm     4     2     8
17  mss      dm     4     3    10
18  mss      dm     4     4     8
19  mss      dm     4     5     8
20  dps     toc     6     1     9
21  dps     toc     6     2     8
22  dps     toc     6     3    10
23  dps     toc     6     4     8
24  dps     toc     6     5     8

In [36]:
pd.merge(df1,df2)

  name     sub  id  mark
0  vha  python   3    10
1  psp     fsd   2     8
2  vby     coa   1     9
3  mss      dm   4     8

In [37]:
pd.merge(df1,df2,left_index=True,right_index=True)

  name     sub  id_x  id_y  mark
0  vha  python     3     1     9
1  psp     fsd     2     2     8
2  vby     coa     1     3    10
3  mss      dm     4     4     8
4  dps     toc     6     5     8

In [39]:
pd.merge(df1,df2,left_index=True,right_index=True,suffixes=("_df1","_df2"))

  name     sub  id_df1  id_df2  mark
0  vha  python       3       1     9
1  psp     fsd       2       2     8
2  vby     coa       1       3    10
3  mss      dm       4       4     8
4  dps     toc       6       5     8

In [40]:
df1=pd.DataFrame({"name":["vha","psp","vby","mss","dps"],"sub":["python","fsd","coa","dm","toc"],"in":[3,2,1,4,6]})
df2=pd.DataFrame({"id":[1,2,3,4,5],"mark":[9,8,10,8,8]})

In [44]:
pd.merge(df1,df2,left_on="in",right_on="id")

  name     sub  in  id  mark
0  vha  python   3   3    10
1  psp     fsd   2   2     8
2  vby     coa   1   1     9
3  mss      dm   4   4     8

In [45]:
df1=pd.DataFrame({"name":["vha","psp","vby","mss","dps"],"sub":["python","fsd","coa","dm","toc"],"id":[3,2,1,4,6]})
df2=pd.DataFrame({"id":[1,2,3,4,5],"mark":[9,8,10,8,8],"fac":["vha","nas","vby","mss","dps"]})

In [46]:
pd.merge(df1,df2,left_on="name",right_on="fac")

  name     sub  id_x  id_y  mark  fac
0  vha  python     3     1     9  vha
1  vby     coa     1     3    10  vby
2  mss      dm     4     4     8  mss
3  dps     toc     6     5     8  dps

In [ ]:
pd.merge(df1,df2,left_on="name",right_on="fac")